### ISSUE TITLE
大佬你好，测试新版又出现了问题

### ISSUE THREAD

**Issue by hecoter** [redrose2100/caterpillar_mail#2]
[![oH1IZF.png](https://s4.ax1x.com/2021/12/11/oH1IZF.png)](https://imgtu.com/i/oH1IZF)
现在完全不能发邮件了……
希望能加个qq以便以后交流，1203083157

**Comment by redrose2100** [comment]
pip install -U caterpillar_mail==1.1.1 加我微信吧，qq我不怎么用了，微信搜 15051876412

**Comment by redrose2100** [comment]
pip install -U caterpillar_mail==1.1.1 加我微信吧，qq我不怎么用了，微信搜 15051876412


| |
redrose2100
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年12月11日 ***@***.***> 写道：


现在完全不能发邮件了……

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by redrose2100** [comment]
已解决，使用如下命令 pip install -U caterpillar_mail==1.1.1 更新至最新版本
